(() => {
  'use strict';
  const COLORS = {BDC1:'#0077B6',BDC2:'#F28E2B',BDC3:'#D84A4A',BDC22:'#C45AC6',BDC222:'#7B61A8',BDC23:'#6C9A3E',BDC106:'#D4A017',BDC107:'#7A9E9F',BDC777:'#D65B8C',BDC888:'#D96C2F',BDC999:'#59A14F','เมฆขาว1':'#8C3FC7'};
  const STATUS_CLASS = {'เสร็จแล้ว':'done','กำลังทำ':'doing','ล่าช้า':'late','ยังไม่เริ่ม':'wait'};
  const DB_NAME = 'repair-master-photos-v7', STORE = 'photos', META_KEY = 'repair-photo-meta-v7', DETAIL_META_KEY = 'repair-detail-photo-meta-v7', DATA_KEY = 'repair-dashboard-data-v7';
  let tasks = [], summaries = [], photoMeta = [], detailItems = [], detailPhotoMeta = [], gallery = [], gallerySource = [], galleryIndex = 0, viewerUrl = '';
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const color = vessel => COLORS[vessel] || '#568091';
  const dateLabel = value => value ? value.split('-').reverse().join('/') : '—';
  const datePair = (a,b) => a ? `${dateLabel(a)}${b ? ' – '+dateLabel(b) : ''}` : '—';
  const statusClass = s => STATUS_CLASS[s] || 'wait';
  const notice = (message, error=false) => { const n=$('#notice'); n.textContent=message; n.style.background=error?'#fee7e5':''; n.style.color=error?'#9d302c':''; n.classList.add('show'); setTimeout(()=>n.classList.remove('show'),6000); };

  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async function replacePhotos(items){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE);store.clear();items.forEach(item=>store.put(item));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
  async function getPhoto(id){const db=await openDb();const value=await new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return value;}
  async function photoSource(item){if(item?.url)return{url:item.url,temporary:false};const rec=await getPhoto(item?.id);return rec?{url:URL.createObjectURL(rec.blob),temporary:true}:null;}

  function setView(id){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));if(id==='photos')renderPhotos();if(id==='detail-photos')renderDetailPhotos();}
  $$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));

  function vessels(){return [...new Set([...Object.keys(COLORS),...summaries.map(s=>s.vessel),...tasks.map(t=>t.vessel)].filter(Boolean))].filter(v=>tasks.some(t=>t.vessel===v)||summaries.some(s=>s.vessel===v));}
  function renderFilters(){const ships=vessels(), shipOptions='<option value="">ทุกลำ</option>'+ships.map(v=>`<option>${esc(v)}</option>`).join('');$('#shipFilter').innerHTML=shipOptions;$('#photoShip').innerHTML=shipOptions;$('#detailShip').innerHTML=shipOptions;const statuses=[...new Set(tasks.map(t=>t.status).filter(Boolean))];$('#statusFilter').innerHTML='<option value="">ทุกสถานะ</option>'+statuses.map(s=>`<option>${esc(s)}</option>`).join('');}
  function renderKpis(){const done=tasks.filter(t=>t.status==='เสร็จแล้ว').length, doing=tasks.filter(t=>t.status==='กำลังทำ').length, late=tasks.filter(t=>t.status==='ล่าช้า').length;$('#kpis').innerHTML=[['Task ที่ใช้งาน',tasks.length],['เสร็จแล้ว',done],['กำลังทำ',doing],['ล่าช้า',late]].map(([label,value])=>`<div class="card kpi"><span>${label}</span><strong>${value}</strong></div>`).join('');}
  function renderVessels(){$('#vessels').innerHTML=vessels().map(v=>{const list=tasks.filter(t=>t.vessel===v),done=list.filter(t=>t.status==='เสร็จแล้ว').length,pct=list.length?Math.round(done/list.length*100):0;return `<article class="card vessel" style="--ship:${color(v)}"><div class="vessel-top"><h3>${esc(v)}</h3><span class="pill">${list.length} งาน</span></div><div class="bar"><i style="width:${pct}%"></i></div><small>เสร็จแล้ว ${done} งาน · ${pct}%</small></article>`;}).join('')||'<div class="empty">ไม่พบรายการเรือ</div>';}
  function filteredTasks(){const q=$('#search').value.trim().toLowerCase(),ship=$('#shipFilter').value,status=$('#statusFilter').value;return tasks.filter(t=>(!ship||t.vessel===ship)&&(!status||t.status===status)&&(!q||[t.id,t.vessel,t.section,t.work].join(' ').toLowerCase().includes(q)));}
  function renderTasks(){const list=filteredTasks();$('#taskRows').innerHTML=list.length?list.map(t=>`<tr><td class="task-id">${esc(t.id)}</td><td><span class="ship-tag" style="--ship:${color(t.vessel)}">${esc(t.vessel)}</span></td><td><b>${esc(t.section||'ไม่ระบุส่วนงาน')}</b><br><span>${esc(t.work)}</span></td><td><span class="status ${statusClass(t.status)}">${esc(t.status||'ไม่ระบุ')}</span></td><td class="dates">${datePair(t.planStart,t.planEnd)}</td><td class="dates">${datePair(t.actualStart,t.actualEnd)}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">ไม่พบงานตามตัวกรอง</td></tr>`;}

  function renderGantt(){
    const DAY=864e5;
    const dated=tasks.flatMap(t=>[t.planStart,t.planEnd,t.actualStart,t.actualEnd]).filter(Boolean).map(Date.parse);
    if(!dated.length){$('#ganttChart').innerHTML='<div class="empty">ยังไม่มีข้อมูลวันที่</div>';return;}
    const first=new Date(Math.min(...dated)),last=new Date(Math.max(...dated));
    const start=Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),1);
    const end=Date.UTC(last.getUTCFullYear(),last.getUTCMonth()+1,0);
    const segments=[],months=[];
    for(let cursor=start;cursor<=end;){
      const date=new Date(cursor),year=date.getUTCFullYear(),month=date.getUTCMonth();
      const monthEnd=Date.UTC(year,month+1,0),lastDay=new Date(monthEnd).getUTCDate(),monthSegments=[];
      for(let day=1;day<=lastDay;day+=7){
        const segStart=Date.UTC(year,month,day),segEnd=Math.min(Date.UTC(year,month,day+6),monthEnd),endDay=new Date(segEnd).getUTCDate();
        const segment={start:segStart,end:segEnd,days:Math.round((segEnd-segStart)/DAY)+1,label:day===endDay?String(day):`${day}–${endDay}`,monthEnd:segEnd===monthEnd};
        segments.push(segment);monthSegments.push(segment);
      }
      months.push({label:date.toLocaleDateString('th-TH',{month:'short',year:'2-digit',timeZone:'UTC'}),count:monthSegments.length});
      cursor=Date.UTC(year,month+1,1);
    }
    const coordinate=value=>{
      const ms=Math.max(start,Math.min(end+DAY,Date.parse(value)));
      let index=segments.findIndex(s=>ms>=s.start&&ms<s.end+DAY);
      if(index<0)index=ms<=start?0:segments.length-1;
      const segment=segments[index];
      return index+Math.max(0,Math.min(1,(ms-segment.start)/(segment.days*DAY)));
    };
    const bar=(a,b,cls)=>{if(!a)return'';const left=coordinate(a),right=coordinate(new Date(Date.parse(b||a)+DAY).toISOString().slice(0,10));return `<i class="${cls}" style="left:${left/segments.length*100}%;width:${Math.max(.22,(right-left)/segments.length*100)}%"></i>`;};
    let offset=2;
    const monthHead=months.map(m=>{const html=`<div class="g-month" style="grid-column:${offset}/span ${m.count}">${m.label}</div>`;offset+=m.count;return html;}).join('');
    const gridStyle=`--segments:${segments.length};min-width:${Math.max(1080,270+segments.length*62)}px`;
    const heads=`<div class="g-months" style="${gridStyle}"><div class="g-corner">Task / เรือ</div>${monthHead}</div><div class="g-weeks" style="${gridStyle}"><div class="g-corner">ช่วงวันที่</div>${segments.map(s=>`<div class="g-week">${s.label}</div>`).join('')}</div>`;
    const rows=tasks.map(t=>`<div class="g-row" style="${gridStyle}"><div class="g-name" style="border-left:4px solid ${color(t.vessel)}"><b>${esc(t.id)} · ${esc(t.vessel)}</b><small>${esc(t.work)}</small></div>${segments.map(s=>`<div class="g-cell${s.monthEnd?' month-end':''}"></div>`).join('')}<div class="track">${bar(t.planStart,t.planEnd,'plan')}${bar(t.actualStart,t.actualEnd,'actual')}</div></div>`).join('');
    $('#ganttChart').innerHTML=heads+rows;
    $('#ganttRange').textContent=`1 ช่อง = 7 วัน · ${dateLabel(new Date(start).toISOString().slice(0,10))} – ${dateLabel(new Date(end).toISOString().slice(0,10))} · ${segments.length} ช่อง`;
  }
  function renderAll(){renderFilters();renderKpis();renderVessels();renderTasks();renderGantt();renderPhotos();renderDetailPhotos();}
  ['search','shipFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTasks));
  ['photoSearch','photoShip'].forEach(id=>$('#'+id).addEventListener(id==='photoSearch'?'input':'change',renderPhotos));
  ['detailSearch','detailShip'].forEach(id=>$('#'+id).addEventListener(id==='detailSearch'?'input':'change',renderDetailPhotos));

  const parser = new DOMParser();
  const xmlText = async(zip,path) => parser.parseFromString(await zip.file(path).async('string'),'application/xml');
  const nodes = (doc,expr,node=doc) => {const out=[],it=doc.evaluate(expr,node,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null);let n;while((n=it.iterateNext()))out.push(n);return out;};
  const node = (doc,expr,parent=doc) => doc.evaluate(expr,parent,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;
  const normalize = (base,target) => {const bits=(base.split('/').slice(0,-1).join('/')+'/'+target).split('/'),out=[];for(const bit of bits){if(!bit||bit==='.')continue;if(bit==='..')out.pop();else out.push(bit);}return out.join('/');};
  const colIndex = ref => {let n=0;for(const c of (ref.match(/[A-Z]+/)||['A'])[0])n=n*26+c.charCodeAt(0)-64;return n-1;};
  const cellValue = (c,shared) => {const type=c.getAttribute('t'),v=node(c.ownerDocument,"./*[local-name()='v']",c)?.textContent||'',inline=node(c.ownerDocument,"./*[local-name()='is']",c)?.textContent||'';return type==='s'?(shared[+v]||''):type==='inlineStr'?inline:type==='b'?v==='1':v;};
  const excelDate = value => {if(value===null||value===undefined||value==='')return'';const v=String(value).trim();if(/^\d{4}-\d\d-\d\d/.test(v))return v.slice(0,10);const m=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m){let y=+m[3];if(y>2400)y-=543;return `${String(y).padStart(4,'0')}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;}const n=+v;if(!Number.isFinite(n))return'';return new Date(Date.UTC(1899,11,30)+n*864e5).toISOString().slice(0,10);};
  async function workbookParts(file){const zip=await JSZip.loadAsync(file),book=await xmlText(zip,'xl/workbook.xml'),rels=await xmlText(zip,'xl/_rels/workbook.xml.rels'),relMap={};nodes(rels,"//*[local-name()='Relationship']").forEach(r=>relMap[r.getAttribute('Id')]=normalize('xl/workbook.xml',r.getAttribute('Target')));const sheets={};nodes(book,"//*[local-name()='sheet']").forEach(s=>sheets[s.getAttribute('name')]=relMap[s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')]);let shared=[];if(zip.file('xl/sharedStrings.xml')){const ss=await xmlText(zip,'xl/sharedStrings.xml');shared=nodes(ss,"//*[local-name()='si']").map(n=>n.textContent);}return{zip,sheets,shared};}
  async function readRows(parts,name){const path=parts.sheets[name];if(!path)throw new Error(`ไม่พบชีต “${name}”`);const doc=await xmlText(parts.zip,path),rows=[];for(const r of nodes(doc,"//*[local-name()='sheetData']/*[local-name()='row']")){const obj={_row:+r.getAttribute('r')};for(const c of nodes(doc,"./*[local-name()='c']",r))obj[colIndex(c.getAttribute('r'))]=cellValue(c,parts.shared);rows.push(obj);}return{rows,path,doc};}
  const compactHeader = value => String(value||'').replace(/[\s/]+/g,'').toLowerCase();
  const headerColumn = (rows,predicate,fallback,headerRow=4) => {const header=rows.find(r=>r._row===headerRow)||{};for(const [key,value] of Object.entries(header)){if(key==='_row')continue;if(predicate(compactHeader(value)))return +key;}return fallback;};
  async function readPictures(parts,sheet,minRow=5,minCol=5,maxCol=9){const out=[],relPath=sheet.path.replace(/([^/]+)$/,'_rels/$1.rels'),rels={};if(parts.zip.file(relPath)){const rdoc=await xmlText(parts.zip,relPath);nodes(rdoc,"//*[local-name()='Relationship']").forEach(r=>rels[r.getAttribute('Id')]=normalize(sheet.path,r.getAttribute('Target')));const drawing=node(sheet.doc,"//*[local-name()='drawing']"),drawPath=drawing&&rels[drawing.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')];if(drawPath&&parts.zip.file(drawPath)){const ddoc=await xmlText(parts.zip,drawPath),drelPath=drawPath.replace(/([^/]+)$/,'_rels/$1.rels'),drels={};if(parts.zip.file(drelPath)){const dr=await xmlText(parts.zip,drelPath);nodes(dr,"//*[local-name()='Relationship']").forEach(r=>drels[r.getAttribute('Id')]=normalize(drawPath,r.getAttribute('Target')));}for(const anchor of nodes(ddoc,"//*[local-name()='oneCellAnchor' or local-name()='twoCellAnchor']")){const row=+(node(ddoc,"./*[local-name()='from']/*[local-name()='row']",anchor)?.textContent||-1)+1,col=+(node(ddoc,"./*[local-name()='from']/*[local-name()='col']",anchor)?.textContent||-1)+1,blip=node(ddoc,".//*[local-name()='blip']",anchor),rid=blip?.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','embed'),media=drels[rid];if(row>=minRow&&col>=minCol&&col<=maxCol&&media&&parts.zip.file(media)){const blob=await parts.zip.file(media).async('blob');out.push({row,col,blob,type:blob.type||`image/${media.split('.').pop()}`});}}}}
    if(parts.zip.file('xl/richData/rdrichvalue.xml')&&parts.zip.file('xl/richData/richValueRel.xml')&&parts.zip.file('xl/richData/_rels/richValueRel.xml.rels')){const values=await xmlText(parts.zip,'xl/richData/rdrichvalue.xml'),links=await xmlText(parts.zip,'xl/richData/richValueRel.xml'),linkRels=await xmlText(parts.zip,'xl/richData/_rels/richValueRel.xml.rels'),mediaById={};nodes(linkRels,"//*[local-name()='Relationship']").forEach(r=>mediaById[r.getAttribute('Id')]=normalize('xl/richData/richValueRel.xml',r.getAttribute('Target')));const ids=nodes(links,"//*[local-name()='rel']").map(r=>r.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')),rich=nodes(values,"//*[local-name()='rv']").map(rv=>+(node(values,"./*[local-name()='v'][1]",rv)?.textContent||-1));for(const c of nodes(sheet.doc,"//*[local-name()='c'][@vm]")){const ref=c.getAttribute('r'),row=+(ref.match(/\d+/)||[0])[0],col=colIndex(ref)+1,valueIndex=+c.getAttribute('vm')-1,media=mediaById[ids[rich[valueIndex]]];if(row>=minRow&&col>=minCol&&col<=maxCol&&media&&parts.zip.file(media)){const blob=await parts.zip.file(media).async('blob');out.push({row,col,blob,type:blob.type||`image/${media.split('.').pop()}`});}}}return out;}

  async function importExcel(file){if(!/\.xlsx$/i.test(file.name))throw new Error('กรุณาเลือกไฟล์ .xlsx');const parts=await workbookParts(file),master=await readRows(parts,'mater69-70'),byRow=new Map(master.rows.map(r=>[r._row,r])),nextTasks=[],nextSummaries=[],cOrder=headerColumn(master.rows,h=>h==='ลำดับ',0),cTask=headerColumn(master.rows,h=>h==='taskid',1),cVessel=headerColumn(master.rows,h=>h.startsWith('เรือ'),2),cSection=headerColumn(master.rows,h=>h.startsWith('แผนก'),3),cStatus=headerColumn(master.rows,h=>h==='สถานะ',4),cWork=headerColumn(master.rows,h=>h==='รายละเอียดงาน',5),cStart=headerColumn(master.rows,h=>h==='เริ่ม',8),cEnd=headerColumn(master.rows,h=>h==='เสร็จ',9),cKind=headerColumn(master.rows,h=>h.includes('แผนงาน')&&h.includes('ผลงาน'),10),cProgress=headerColumn(master.rows,h=>h==='คืบหน้า',255);for(const plan of master.rows.filter(r=>r._row>=7&&String(r[cKind]||'').trim()==='Plan')){const actual=byRow.get(plan._row+1)||{},id=String(plan[cTask]||'').trim(),work=String(plan[cWork]||'').trim(),vessel=String(plan[cVessel]||'').trim();if(work.startsWith('แผนงานรวม'))nextSummaries.push({vessel,planStart:excelDate(plan[cStart]),planEnd:excelDate(plan[cEnd]),actualStart:excelDate(actual[cStart]),actualEnd:excelDate(actual[cEnd])});else if(/^T\d+$/.test(id)&&work)nextTasks.push({id,order:plan[cOrder]||'',vessel,section:String(plan[cSection]||'').trim(),status:String(plan[cStatus]||'').trim(),work,planStart:excelDate(plan[cStart]),planEnd:excelDate(plan[cEnd]),actualStart:excelDate(actual[cStart]),actualEnd:excelDate(actual[cEnd]),progress:+plan[cProgress]||0});}
    if(!nextTasks.length)throw new Error('ไม่พบ Task ที่มีรายละเอียดในชีต mater69-70');const duplicates=nextTasks.map(t=>t.id).filter((id,i,a)=>a.indexOf(id)!==i);if(duplicates.length)throw new Error('พบ Task ID ซ้ำ: '+[...new Set(duplicates)].join(', '));
    const photos=parts.sheets['Daily Photos']?await readRows(parts,'Daily Photos'):null,pictures=photos?await readPictures(parts,photos):[],pictureRows=new Map();for(const pic of pictures){if(!pictureRows.has(pic.row))pictureRows.set(pic.row,[]);pictureRows.get(pic.row).push(pic);}const records=[],meta=[],stamp=Date.now();if(photos){const pVessel=headerColumn(photos.rows,h=>h==='เรือ',0),pTask=headerColumn(photos.rows,h=>h==='taskid',1),pDate=headerColumn(photos.rows,h=>h==='วันที่',2),pDetail=headerColumn(photos.rows,h=>h.startsWith('รายละเอียด'),3);for(const r of photos.rows.filter(x=>x._row>=5&&pictureRows.has(x._row))){for(const pic of (pictureRows.get(r._row)||[]).sort((a,b)=>a.col-b.col)){const id=`P-${stamp}-${r._row}-${pic.col}`;records.push({id,blob:pic.blob,type:pic.type});meta.push({id,vessel:String(r[pVessel]||'').trim(),taskId:String(r[pTask]||'').trim()||'ยังไม่ระบุ Task ID',date:excelDate(r[pDate]),detail:String(r[pDetail]||'').trim(),slot:pic.col-4});}}}
    const details=parts.sheets['รูปภาพรายละเอียดงาน']?await readRows(parts,'รูปภาพรายละเอียดงาน'):null,detailPictures=details?await readPictures(parts,details,2,5,14):[],detailPictureRows=new Map();for(const pic of detailPictures){if(!detailPictureRows.has(pic.row))detailPictureRows.set(pic.row,[]);detailPictureRows.get(pic.row).push(pic);}const nextDetailItems=[],detailRecords=[],detailMeta=[];if(details){const dVessel=headerColumn(details.rows,h=>h==='เรือ',0,1),dTask=headerColumn(details.rows,h=>h==='taskid',1,1),dDate=headerColumn(details.rows,h=>h==='วันที่',2,1),dText=headerColumn(details.rows,h=>h.startsWith('รายละเอียด'),3,1);for(const r of details.rows.filter(x=>x._row>=2)){const vessel=String(r[dVessel]||'').trim(),taskId=String(r[dTask]||'').trim(),date=excelDate(r[dDate]),detail=String(r[dText]||'').trim();if(taskId&&vessel&&detail)nextDetailItems.push({vessel,taskId,date,detail});for(const pic of (detailPictureRows.get(r._row)||[]).sort((a,b)=>a.col-b.col)){const id=`D-${stamp}-${r._row}-${pic.col}`;detailRecords.push({id,blob:pic.blob,type:pic.type});detailMeta.push({id,vessel,taskId:taskId||'ยังไม่ระบุ Task ID',date,detail,slot:pic.col-4});}}}
    tasks=nextTasks;summaries=nextSummaries;photoMeta=meta;detailItems=nextDetailItems;detailPhotoMeta=detailMeta;await replacePhotos([...records,...detailRecords]);localStorage.setItem(META_KEY,JSON.stringify(meta));localStorage.setItem(DETAIL_META_KEY,JSON.stringify(detailMeta));localStorage.setItem(DATA_KEY,JSON.stringify({tasks,summaries,detailItems}));$('#updated').textContent=`${file.name} · ${new Date().toLocaleString('th-TH')}`;renderAll();notice(`อัปเดตแล้ว ${tasks.length} งาน · รูปรายวัน ${photoMeta.length} รูป · รูปรายละเอียด ${detailPhotoMeta.length} รูป`);}

  const photoVessel=p=>p.vessel||tasks.find(t=>t.id===p.taskId)?.vessel||'ไม่ระบุเรือ';
  const photoOrder=(a,b)=>(b.date||'0000').localeCompare(a.date||'0000')||(a.slot||0)-(b.slot||0);
  async function renderPhotos(){
    const grid=$('#photoGrid'),q=$('#photoSearch').value.trim().toLowerCase(),ship=$('#photoShip').value;
    grid.querySelectorAll('[data-object-url]').forEach(el=>URL.revokeObjectURL(el.dataset.objectUrl));
    const filtered=photoMeta.filter(p=>{const task=tasks.find(t=>t.id===p.taskId),v=photoVessel(p);return(!ship||v===ship)&&(!q||[v,p.taskId,p.detail,task?.work].join(' ').toLowerCase().includes(q));});
    const byVessel=new Map();
    for(const p of filtered){const vessel=photoVessel(p);if(!byVessel.has(vessel))byVessel.set(vessel,new Map());const byTask=byVessel.get(vessel);if(!byTask.has(p.taskId))byTask.set(p.taskId,[]);byTask.get(p.taskId).push(p);}
    const vesselGroups=[...byVessel].sort((a,b)=>a[0].localeCompare(b[0],'th',{numeric:true}));
    if(!vesselGroups.length){grid.innerHTML='<div class="card empty">ยังไม่มีรูปจาก Excel หรือไม่พบรูปตามตัวกรอง</div>';return;}
    grid.innerHTML=vesselGroups.map(([vessel,taskMap])=>{const taskGroups=[...taskMap].sort((a,b)=>a[0].localeCompare(b[0],'th',{numeric:true}));const photoCount=taskGroups.reduce((n,[,items])=>n+items.length,0);return `<details class="photo-ship card" style="--ship:${color(vessel)}" open><summary><div><h3>${esc(vessel)}</h3><span>${taskGroups.length} Task · ${photoCount} รูป</span></div></summary><div class="photo-task-grid">${taskGroups.map(([taskId,items])=>{items.sort(photoOrder);const first=items[0],task=tasks.find(t=>t.id===taskId),days=new Set(items.map(p=>p.date).filter(Boolean)).size;return `<button class="photo-task" style="--ship:${color(vessel)}" data-photo="${first.id}"><div class="task-thumb">กำลังโหลด…</div><div class="task-photo-body"><b>${esc(taskId)}</b><span>${days} วัน · ${items.length} รูป · ล่าสุด ${dateLabel(first.date)}</span><small>${esc(first.detail||task?.work||'')}</small></div></button>`;}).join('')}</div></details>`;}).join('');
    for(const card of $$('[data-photo]',grid)){card.addEventListener('click',()=>openGallery(card.dataset.photo,'daily'));const item=photoMeta.find(p=>p.id===card.dataset.photo),source=await photoSource(item);if(source){const thumb=$('.task-thumb',card);thumb.textContent='';thumb.style.backgroundImage=`url(${source.url})`;if(source.temporary)thumb.dataset.objectUrl=source.url;}}
  }
  async function renderDetailPhotos(){
    const grid=$('#detailPhotoGrid'),q=$('#detailSearch').value.trim().toLowerCase(),ship=$('#detailShip').value;
    grid.querySelectorAll('[data-object-url]').forEach(el=>URL.revokeObjectURL(el.dataset.objectUrl));
    const groups=new Map(),add=(item,photo=null)=>{const vessel=item.vessel||'ไม่ระบุเรือ',taskId=item.taskId||'ยังไม่ระบุ Task ID';if(ship&&vessel!==ship)return;if(q&&![vessel,taskId,item.detail].join(' ').toLowerCase().includes(q))return;if(!groups.has(vessel))groups.set(vessel,new Map());const tasksMap=groups.get(vessel);if(!tasksMap.has(taskId))tasksMap.set(taskId,{item,photos:[]});if(photo)tasksMap.get(taskId).photos.push(photo);};
    detailItems.forEach(item=>add(item));detailPhotoMeta.forEach(photo=>add(photo,photo));
    const vesselGroups=[...groups].sort((a,b)=>a[0].localeCompare(b[0],'th',{numeric:true}));$('#detailPhotoCount').textContent=`${detailItems.length} Task · ${detailPhotoMeta.length} รูป`;
    if(!vesselGroups.length){grid.innerHTML='<div class="card empty">ไม่พบรายการตามตัวกรอง</div>';return;}
    grid.innerHTML=vesselGroups.map(([vessel,taskMap],index)=>{const taskGroups=[...taskMap].sort((a,b)=>a[0].localeCompare(b[0],'th',{numeric:true})),photoCount=taskGroups.reduce((n,[,entry])=>n+entry.photos.length,0);return `<details class="photo-ship card" style="--ship:${color(vessel)}" ${ship||index===0?'open':''}><summary><div><h3>${esc(vessel)}</h3><span>${taskGroups.length} Task · ${photoCount} รูป</span></div></summary><div class="photo-task-grid">${taskGroups.map(([taskId,entry])=>{entry.photos.sort(photoOrder);const first=entry.photos[0],tag=first?`button data-detail-photo="${first.id}"`:'div',endTag=first?'button':'div';return `<${tag} class="photo-task${first?'':' no-photo'}" style="--ship:${color(vessel)}"><div class="task-thumb">${first?'กำลังโหลด…':'ยังไม่มีรูป'}</div><div class="task-photo-body"><b>${esc(taskId)}</b><span>${first?`${entry.photos.length} รูป${first.date?' · '+dateLabel(first.date):''}`:'พร้อมรับรูปที่ 1–10'}</span><small>${esc(entry.item.detail||'')}</small></div></${endTag}>`;}).join('')}</div></details>`;}).join('');
    for(const card of $$('[data-detail-photo]',grid)){card.addEventListener('click',()=>openGallery(card.dataset.detailPhoto,'detail'));const item=detailPhotoMeta.find(p=>p.id===card.dataset.detailPhoto),source=await photoSource(item);if(source){const thumb=$('.task-thumb',card);thumb.textContent='';thumb.style.backgroundImage=`url(${source.url})`;if(source.temporary)thumb.dataset.objectUrl=source.url;}}
  }
  async function openGallery(id,kind='daily'){gallerySource=kind==='detail'?detailPhotoMeta:photoMeta;const selected=gallerySource.find(p=>p.id===id);if(!selected)return;const vessel=photoVessel(selected);gallery=gallerySource.filter(p=>p.taskId===selected.taskId&&photoVessel(p)===vessel).sort(photoOrder);galleryIndex=Math.max(0,gallery.findIndex(p=>p.id===id));await showGallery();$('#viewer').showModal();}
  async function showGallery(){const item=gallery[galleryIndex],source=await photoSource(item),task=tasks.find(t=>t.id===item.taskId);if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl=source?.temporary?source.url:'';$('#viewerImg').src=source?.url||'';$('#viewerTitle').textContent=`${item.vessel||task?.vessel||'ไม่ระบุเรือ'} · ${item.taskId}`;$('#viewerMeta').textContent=[dateLabel(item.date),item.detail||task?.work].filter(Boolean).join(' · ');$('#counter').textContent=`${galleryIndex+1} / ${gallery.length}`;$('#prev').disabled=$('#next').disabled=gallery.length<2;}
  $('#prev').addEventListener('click',async()=>{galleryIndex=(galleryIndex-1+gallery.length)%gallery.length;await showGallery();});$('#next').addEventListener('click',async()=>{galleryIndex=(galleryIndex+1)%gallery.length;await showGallery();});$('#viewerClose').addEventListener('click',()=>$('#viewer').close());$('#viewer').addEventListener('close',()=>{if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl='';});
  $('#file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{await importExcel(file);}catch(err){console.error(err);notice(err.message||'ไม่สามารถอ่านไฟล์ได้',true);}finally{e.target.value='';}});

  async function loadFallbackData(){try{const r=await fetch('data.json',{cache:'no-store'});if(!r.ok)throw new Error('data.json unavailable');const data=await r.json();tasks=data.tasks||[];summaries=data.summaries||[];photoMeta=data.photos||[];detailItems=data.detailItems||[];detailPhotoMeta=data.detailPhotos||[];renderAll();}catch{notice('ไม่สามารถโหลดข้อมูลตั้งต้น กรุณาอัปโหลด Excel',true);renderAll();}}
  async function loadInitialData(){try{const r=await fetch(`masterplan.xlsx?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('masterplan.xlsx unavailable');const blob=await r.blob();const file=new File([blob],'masterplan.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});await importExcel(file);$('#updated').textContent=`masterplan.xlsx · โหลดอัตโนมัติ ${new Date().toLocaleString('th-TH')}`;}catch(err){console.warn('Auto-load masterplan.xlsx failed; using data.json',err);await loadFallbackData();}}
  loadInitialData();
})();
